
collateInfantsRecords <- function(conn,
                                  hes_apc_tables,
                                  base_directory_path,
                                  ir_name) {

  fields_of_interest <- c("epikey",
                          "token_person_id",
                          "admidate",
                          "classpat",
                          "disdate",
                          "epistart",
                          "epiend",
                          "epiorder",
                          "epitype",
                          "admimeth",
                          "dismeth",
                          "birordr_1 AS birordr",
                          "biresus_1 AS biresus",
                          "birstat_1 AS birstat",
                          "birweit_1 AS birweit",
                          "delmeth_1 AS delmeth",
                          "delstat_1 AS delstat",
                          "gestat_1 AS gestat",
                          "sexbaby_1 AS sexbaby",
                          "hrgnhs",
                          "sushrg",
                          "suscorehrg",
                          "matage",
                          "neocare",
                          "numbaby",
                          "well_baby_ind",
                          "mydob",
                          "admiage",
                          "activage",
                          "startage",
                          "endage",
                          "sex",
                          "ethnos",
                          "oacode6",
                          "msoa01",
                          "msoa11",
                          "imd04_decile",
                          "resgor",
                          "cr_residence")

  diag_cols <- paste0("diag_",
                      formatC(1:20, width = 2, flag = "0", format = "d"))

  sql_query <- paste("SELECT dat.* FROM (",
                     "SELECT token_person_id FROM (",
                     paste("SELECT token_person_id FROM",
                           hes_apc_tables,
                           "WHERE",
                           "epistat = '3' AND",
                           "(",
                           "startage IN ('7001', '7002', '7003') OR",
                           "endage IN ('7001', '7002', '7003') OR",
                           "(",
                           "mydob NOT IN ('011800', '011801') AND (",
                           "mydob = SUBSTRING(admidate, 6, 2) + SUBSTRING(admidate, 1, 4) OR",
                           "mydob = SUBSTRING(disdate, 6, 2) + SUBSTRING(disdate, 1, 4) OR",
                           "mydob = SUBSTRING(epistart, 6, 2) + SUBSTRING(epistart, 1, 4) OR",
                           "mydob = SUBSTRING(epiend, 6, 2) + SUBSTRING(epiend, 1, 4)",
                           ")))",
                           collapse = " UNION ALL "),
                     ") AS sq GROUP BY token_person_id) AS tpis INNER JOIN (",
                     paste("SELECT",
                           substring(hes_apc_tables, 21),
                           "AS reporting_year_start,",
                           paste0(c(fields_of_interest,
                                    diag_cols),
                                  collapse = ", "),
                           "FROM",
                           hes_apc_tables,
                           "WHERE",
                           "epistat = '3'",
                           collapse = " UNION ALL "),
                     ") AS dat ON (",
                     "tpis.token_person_id = dat.token_person_id",
                     ");")


  infants_records <- executeQuery(conn, sql_query)

  write_result <- writeParquetFile(infants_records,
                                   dir_path = paste0(base_directory_path,
                                                     ir_name),
                                   filename = ir_name)

  return(write_result)
}
