createBirthCohort <- function(ddb_conn,
                              ms_conn,
                              base_directory_path,
                              infants_records_name,
                              births_deaths_name,
                              nhs_dfe_id_lookup_name,
                              birth_cohort_name) {

  # ddb_conn <- duckdb_conn
  # ms_conn <- mssql_conn
  # base_directory_path <- echoccs_data_directory_path

  infant_records_data_path <- paste0(base_directory_path,
                                     infants_records_name,
                                     "/",
                                     infants_records_name,
                                     ".parquet")

  births_deaths_path <- paste0(base_directory_path,
                               births_deaths_name,
                               "/",
                               births_deaths_name,
                               ".parquet")

  nhs_dfe_id_lookup_path <- paste0(base_directory_path,
                               nhs_dfe_id_lookup_name,
                               "/",
                               nhs_dfe_id_lookup_name,
                               ".parquet")

  date_fields <- c("admidate",
                   "disdate",
                   "epiend",
                   "epistart")


  diag_fields <- paste0("diag_",
                        formatC(1:20, width = 2, flag = "0", format = "d"))

  int_age_fields <- c("activage",
                      "admiage")

  coded_age_fields <- c("startage",
                        "endage")

  hrg_fields <- c("hrgnhs",
                  "sushrg",
                  "suscorehrg")


  sql_infant_records_raw <- paste("DROP TABLE IF EXISTS infant_records_raw;",
                                  "CREATE TABLE infant_records_raw AS (",
                                  "SELECT",
                                  paste0(c("reporting_year_start",
                                           "epikey",
                                           "token_person_id",
                                           "classpat",
                                           "epitype",
                                           "admimeth",
                                           "dismeth",
                                           "birordr",
                                           "biresus",
                                           "birstat",
                                           "birweit",
                                           "delmeth",
                                           "delstat",
                                           "gestat",
                                           "sexbaby",
                                           hrg_fields,
                                           "matage",
                                           "neocare",
                                           "numbaby",
                                           "well_baby_ind",
                                           "sex",
                                           "ethnos",
                                           "oacode6",
                                           "msoa01",
                                           "msoa11",
                                           "imd04_decile",
                                           "resgor",
                                           "cr_residence",
                                           paste0("TRY_CAST(CASE WHEN ",
                                                  date_fields,
                                                  " IN ('1800-01-01', '1801-01-01') ",
                                                  "THEN NULL ELSE ",
                                                  date_fields,
                                                  " END AS DATE) AS ",
                                                  date_fields),
                                           paste0("TRY_CAST(CASE WHEN mydob IN ",
                                                  "('011800', '011801') THEN NULL ",
                                                  "ELSE CONCAT(",
                                                  "SUBSTRING(mydob, 3, 4), '-', ",
                                                  "SUBSTRING(mydob, 1, 2), '-01') END AS DATE) ",
                                                  "AS mydob"),
                                           paste0("SUBSTRING(",
                                                  diag_fields,
                                                  ", 1, 4) AS ",
                                                  diag_fields),
                                           paste0("CAST(CASE WHEN ",
                                                  int_age_fields,
                                                  " IN ('', '999') THEN NULL ELSE ",
                                                  int_age_fields,
                                                  " END AS INT) AS ",
                                                  int_age_fields),
                                           paste0("CASE WHEN ",
                                                  coded_age_fields,
                                                  " = '' THEN NULL ELSE ",
                                                  coded_age_fields,
                                                  " END AS ",
                                                  coded_age_fields),
                                           paste0("CAST(CASE WHEN epiorder IN ",
                                                  "('', '98', '99') THEN NULL ELSE ",
                                                  "epiorder END ",
                                                  "AS INT) AS epiorder")),
                                         collapse = ", "),
                                  "FROM",
                                  paste0("read_parquet('",
                                         infant_records_data_path,
                                         "')"),
                                  ");")

  res <- executeQuery(ddb_conn,
                      sql_query = sql_infant_records_raw,
                      query_type = "SEND")

  sql_infant_records_temp <- paste("DROP TABLE IF EXISTS infant_records_temp;",
                                   "CREATE TABLE infant_records_temp AS (",
                                   "SELECT *,",
                                   "CASE WHEN reporting_year_start < 2021 AND resgor IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K') THEN 1",
                                   "WHEN reporting_year_start >= 2021 AND LEN(CR_RESIDENCE) = 3 AND CR_RESIDENCE != 'Q99' THEN 1",
                                   "WHEN reporting_year_start < 2021 AND resgor IN ('S', 'W', 'X', 'Z') THEN 0",
                                   "WHEN reporting_year_start >= 2021 AND CR_RESIDENCE IN ('Q99', 'S', 'X', 'Z') THEN 0",
                                   "ELSE NULL END AS resgor_england,",
                                   "LEAST(",
                                   paste0(date_fields,
                                          collapse = ", "),
                                   ") AS episode_min_date,",
                                   "CASE WHEN (",
                                   paste0("SUBSTRING(", diag_fields, ", 1, 3) IN (",
                                          paste0("'", paste0("Z", 37:38), "'",
                                                 collapse = ", "),
                                          ")",
                                          collapse = " OR "),
                                   "OR",
                                   paste0("SUBSTRING(", hrg_fields, ", 1, 3) IN (",
                                          paste0("'", paste0("N0", 1:5), "'",
                                                 collapse = ", "),
                                          ") OR ",
                                          "SUBSTRING(", hrg_fields, ", 1, 4) IN (",
                                          paste0("'", paste0("PB0", 1:6), "'",
                                                 collapse = ", "),
                                          ")",
                                          collapse = " OR "),
                                   "OR",
                                   "epitype IN ('3', '6') OR",
                                   "classpat IN ('5') OR",
                                   "admimeth IN ('82', '83', '2C') OR",
                                   "neocare IN (",
                                   paste0("'", 0:4 , "'", collapse = ", "),
                                   ")) THEN 1 ELSE 0 END AS birth_record,",
                                   "CASE WHEN (",
                                   paste0("SUBSTRING(", diag_fields, ", 1, 4) IN ('P964')",
                                          collapse = " OR "),
                                   ") THEN 1 ELSE 0 END AS termination_record,",
                                   "CASE WHEN (",
                                   paste0("SUBSTRING(", diag_fields, ", 1, 3) IN ('P95')",
                                          collapse = " OR "), "OR",
                                   paste0("SUBSTRING(", diag_fields, ", 1, 4) IN (",
                                          paste0("'Z37", c(1, 3, 6, 7), "'",
                                                 collapse = ", "),
                                          ")",
                                          collapse = " OR "), "OR",
                                   "dismeth IN ('5') OR",
                                   "birstat IN (",
                                   paste0("'", 2:4 , "'", collapse = ", "),
                                   ")) THEN 1 ELSE 0 END AS stillbirth_record,",
                                   "CASE WHEN (",
                                   paste0("SUBSTRING(", diag_fields, ", 1, 4) IN (",
                                          paste0("'",
                                                 c(paste0("Z37", 0:1),
                                                   paste0("Z38", 0:2)),
                                                 "'",
                                                 collapse = ", "),
                                          ")",
                                          collapse = " OR "),
                                   ") THEN 1 ELSE 0 END AS singleton_diag_birth_record,",
                                   "CASE WHEN (",
                                   paste0("SUBSTRING(", diag_fields, ", 1, 4) IN (",
                                          paste0("'",
                                                 c(paste0("Z37", 2:7),
                                                   paste0("Z38", 3:8)),
                                                 "'",
                                                 collapse = ", "),
                                          ")",
                                          collapse = " OR "), "OR",
                                   "birordr IN (",
                                   paste0("'", 2:7, "'",
                                          collapse = ", "),
                                   ") OR",
                                   "numbaby IN (",
                                   paste0("'", 2:6, "'",
                                          collapse = ", "),
                                   ")",
                                   ") THEN 1 ELSE 0 END AS multiple_birth_record,",
                                   "FROM infant_records_raw);",
                                   "DROP TABLE IF EXISTS infant_records_raw;")

  res <- executeQuery(ddb_conn,
                      sql_query = sql_infant_records_temp,
                      query_type = "SEND")
  gc()

  sql_infant_records <- paste("DROP TABLE IF EXISTS infant_records;",
                              "CREATE TABLE infant_records AS (",
                              "SELECT dat.*,",
                              "ROW_NUMBER() OVER (PARTITION BY dat.token_person_id ORDER BY episode_min_date, epistart, epiorder, epikey) AS record_order,",
                              "(dat.episode_min_date - grp.min_recorded_date) AS days_since_min_recorded_date,",
                              "DATEDIFF('MONTH', mydob, episode_min_date) AS months_after_dob,",
                              "grp.min_recorded_date,",
                              "grp.any_missing_episode_min_date",
                              "FROM infant_records_temp AS dat INNER JOIN (",
                              "SELECT",
                              "token_person_id,",
                              "MIN(episode_min_date) AS min_recorded_date,",
                              "MAX(CASE WHEN episode_min_date IS NULL THEN 1 ELSE 0 END) AS any_missing_episode_min_date",
                              "FROM infant_records_temp",
                              "GROUP BY token_person_id) AS grp ON",
                              "dat.token_person_id = grp.token_person_id",
                              ");",
                              "DROP TABLE IF EXISTS infant_records_temp;")

  res <- executeQuery(ddb_conn,
                      sql_query = sql_infant_records,
                      query_type = "SEND")
  gc()

  sql_infant_records_summary <- paste("DROP TABLE IF EXISTS infant_records_summary;",
                                      "CREATE TABLE infant_records_summary AS (",
                                      "SELECT",
                                      "grp5.*,",
                                      "residency.resgor_england,",
                                      "DATEDIFF('MONTH', grp5.min_dob, residency.resgor_england_date) AS resgor_england_months_since_min_dob",
                                      "FROM (",
                                      "SELECT",
                                      "grp4.*,",
                                      "min_age_epidate.min_epiage,",
                                      "min_age_epidate.min_epiage_epidate",
                                      "FROM (",
                                      "SELECT",
                                      "grp3.*,",
                                      "sexbaby_n.n_sexbaby",
                                      "FROM (",
                                      "SELECT",
                                      "grp2.*,",
                                      "sexbaby_min.sexbaby AS sexbaby_earliest",
                                      "FROM (",
                                      "SELECT",
                                      "grp1.*,",
                                      "sex_min.sex AS sex_earliest,",
                                      "FROM (",
                                      "SELECT",
                                      "token_person_id,",
                                      "MAX(any_missing_episode_min_date) AS any_missing_episode_min_date,",
                                      "COUNT(DISTINCT CASE WHEN sex IN ('1', '2') THEN sex ELSE NULL END) AS n_sex,",
                                      "MAX(CASE WHEN birth_record = 1 AND ABS(months_after_dob) < 2 THEN 1 ELSE 0 END) AS any_birth_record,",
                                      "MAX(CASE WHEN termination_record = 1 AND ABS(months_after_dob) < 2 THEN 1 ELSE 0 END) AS any_termination_record,",
                                      "MAX(CASE WHEN stillbirth_record = 1 AND ABS(months_after_dob) < 2 THEN 1 ELSE 0 END) AS any_stillbirth_record,",
                                      "MAX(CASE WHEN multiple_birth_record = 1 AND ABS(months_after_dob) < 2 THEN 1 ELSE 0 END) AS any_multiple_birth_record,",
                                      "MAX(CASE WHEN singleton_diag_birth_record = 1 AND ABS(months_after_dob) < 2 THEN 1 ELSE 0 END) AS any_singleton_diag_birth_record,",
                                      "SUM(CASE WHEN ABS(months_after_dob) < 2 THEN 1 ELSE 0 END) AS records_within_1_month_of_dob,",
                                      "COUNT(*) AS records,",
                                      "SUM(CASE WHEN days_since_min_recorded_date < 29 THEN 1 ELSE 0 END) AS recs_28days,",
                                      "SUM(CASE WHEN days_since_min_recorded_date <= 3 * 365 THEN 1 ELSE 0 END) AS recs_3yrs,",
                                      "MIN(reporting_year_start) AS reporting_year_start,",
                                      "MAX(CASE WHEN ABS(months_after_dob) < 2 AND (startage IN ('7001', '7002', '7003') OR endage IN ('7001', '7002', '7003')) THEN 1 ELSE 0 END) AS any_baby,",
                                      "MIN(CASE WHEN ABS(months_after_dob) < 2 AND startage IN ('7001', '7002', '7003') THEN startage::INT ELSE NULL END) AS min_startage,",
                                      "MIN(CASE WHEN ABS(months_after_dob) < 2 AND endage IN ('7001', '7002', '7003') THEN endage::INT ELSE NULL END) AS min_endage,",
                                      "MIN(months_after_dob) AS min_months_after_dob,",
                                      "MIN(episode_min_date) AS first_admi,",
                                      "MAX(episode_min_date) AS last_admi,",
                                      "MIN(mydob) AS min_dob,",
                                      "COUNT(DISTINCT mydob) AS n_dob,",
                                      "LEAST(",
                                      paste0("MIN(",
                                             int_age_fields,
                                             ")",
                                             collapse = ", "),
                                      ") AS min_age,",
                                      "GREATEST(",
                                      paste0("MAX(",
                                             int_age_fields,
                                             ")",
                                             collapse = ", "),
                                      ") AS max_age",
                                      "FROM infant_records",
                                      "GROUP BY token_person_id) AS grp1",
                                      "LEFT JOIN (",
                                      "SELECT",
                                      "sex_grp.token_person_id,",
                                      "sex_ir.sex",
                                      "FROM (",
                                      "SELECT",
                                      "token_person_id,",
                                      "MIN(record_order) AS sex_record_order",
                                      "FROM infant_records",
                                      "WHERE sex IN ('1', '2')",
                                      "GROUP BY token_person_id) AS sex_grp",
                                      "INNER JOIN infant_records sex_ir ON (",
                                      "sex_grp.token_person_id = sex_ir.token_person_id AND",
                                      "sex_grp.sex_record_order = sex_ir.record_order",
                                      ")) AS sex_min ON",
                                      "grp1.token_person_id = sex_min.token_person_id",
                                      ") AS grp2",
                                      "LEFT JOIN (",
                                      "SELECT",
                                      "sexbaby_grp.token_person_id,",
                                      "sexbaby_ir.sexbaby",
                                      "FROM (",
                                      "SELECT",
                                      "token_person_id,",
                                      "MIN(record_order) AS sexbaby_record_order",
                                      "FROM infant_records",
                                      "WHERE sexbaby IN ('1', '2') AND ABS(months_after_dob) < 2",
                                      "GROUP BY token_person_id) AS sexbaby_grp",
                                      "INNER JOIN infant_records sexbaby_ir ON (",
                                      "sexbaby_grp.token_person_id = sexbaby_ir.token_person_id AND",
                                      "sexbaby_grp.sexbaby_record_order = sexbaby_ir.record_order",
                                      ")) AS sexbaby_min ON",
                                      "grp2.token_person_id = sexbaby_min.token_person_id",
                                      ") AS grp3",
                                      "LEFT JOIN (",
                                      "SELECT",
                                      "token_person_id,",
                                      "COUNT(DISTINCT CASE WHEN sexbaby IN ('1', '2') THEN sexbaby ELSE NULL END) AS n_sexbaby",
                                      "FROM infant_records",
                                      "WHERE ABS(months_after_dob) < 2",
                                      "GROUP BY token_person_id",
                                      ") AS sexbaby_n ON",
                                      "grp3.token_person_id = sexbaby_n.token_person_id",
                                      ") AS grp4",
                                      "LEFT JOIN (",
                                      "SELECT",
                                      "token_person_id,",
                                      "epiage AS min_epiage,",
                                      "epidate AS min_epiage_epidate",
                                      "FROM (",
                                      "SELECT",
                                      "token_person_id,",
                                      "epiage,",
                                      "epidate",
                                      "FROM (",
                                      "SELECT",
                                      "token_person_id,",
                                      "ROW_NUMBER() OVER (PARTITION BY token_person_id ORDER BY epiage, epidate, epikey) AS ordr_epiage,",
                                      "epiage,",
                                      "epidate",
                                      "FROM (",
                                      "SELECT",
                                      "token_person_id,",
                                      "epikey,",
                                      "CASE WHEN startage IN ('7001', '7002', '7003') AND epistart IS NOT NULL THEN startage::INT",
                                      "WHEN (startage NOT IN ('7001', '7002', '7003') OR epistart IS NULL) AND (endage IN ('7001', '7002', '7003') AND epiend IS NOT NULL) THEN endage::INT",
                                      "ELSE NULL END AS epiage,",
                                      "CASE WHEN startage IN ('7001', '7002', '7003') AND epistart IS NOT NULL THEN epistart",
                                      "WHEN (startage NOT IN ('7001', '7002', '7003') OR epistart IS NULL) AND (endage IN ('7001', '7002', '7003') AND epiend IS NOT NULL) THEN epiend",
                                      "ELSE NULL END AS epidate",
                                      "FROM infant_records",
                                      "WHERE (startage IN ('7001', '7002', '7003') AND epistart IS NOT NULL) OR",
                                      "(endage IN ('7001', '7002', '7003') AND epiend IS NOT NULL)) AS sq_epiage",
                                      ") AS sq_epiage_ordr WHERE ordr_epiage = 1",
                                      ") AS sq_epiage_ordr1) AS min_age_epidate ON",
                                      "grp4.token_person_id = min_age_epidate.token_person_id",
                                      ") AS grp5",
                                      "LEFT JOIN (",
                                      "SELECT",
                                      "resgor_grp.token_person_id,",
                                      "resgor_ir.msoa01,",
                                      "resgor_ir.msoa11,",
                                      "resgor_ir.resgor_england,",
                                      "resgor_ir.episode_min_date AS resgor_england_date",
                                      "FROM (",
                                      "SELECT",
                                      "token_person_id,",
                                      "MIN(record_order) AS resgor_record_order",
                                      "FROM infant_records",
                                      "WHERE resgor_england IS NOT NULL",
                                      "AND episode_min_date IS NOT NULL",
                                      "GROUP BY token_person_id) AS resgor_grp",
                                      "INNER JOIN infant_records resgor_ir ON (",
                                      "resgor_grp.token_person_id = resgor_ir.token_person_id AND",
                                      "resgor_grp.resgor_record_order = resgor_ir.record_order",
                                      ")) AS residency ON",
                                      "grp5.token_person_id = residency.token_person_id);",
                                      "DROP TABLE IF EXISTS infant_records;")

  res <- executeQuery(ddb_conn,
                      sql_query = sql_infant_records_summary,
                      query_type = "SEND")


  # Verify only one record per TPI
  tpis_gt2_records_summary <- executeQuery(ddb_conn,
                                              sql_query = paste("SELECT COUNT(*) FROM (",
                                                                "SELECT COUNT(*) AS cnt",
                                                                "FROM infant_records_summary",
                                                                "GROUP BY token_person_id",
                                                                ") AS sq WHERE cnt > 1;"))
  stopifnot(tpis_gt2_records_summary == 0)

  registrations_fields <- c("birth_records",
                            "birth_registration_date",
                            "birth_sex",
                            "birth_stillbirth_records",
                            "death_records",
                            "death_date",
                            "death_date_year_precision_only")

  sql_infant_summary_with_registrations <- paste("DROP TABLE IF EXISTS infant_records_summary_with_registrations;",
                                                 "CREATE TABLE infant_records_summary_with_registrations AS (",
                                                 "SELECT",
                                                 "infants.*,",
                                                 paste0("registrations.",
                                                        registrations_fields,
                                                        collapse = ", "),
                                                 "FROM infant_records_summary AS infants LEFT JOIN",
                                                 paste0("read_parquet('",
                                                        births_deaths_path,
                                                        "') AS registrations"),
                                                 "ON infants.token_person_id = registrations.token_person_id);",
                                                 "DROP TABLE IF EXISTS infant_records_summary;")

  res <- executeQuery(ddb_conn,
                      sql_query = sql_infant_summary_with_registrations,
                      query_type = "SEND")
  gc()

  # Verify birth notifications data is 1 record per TPI
  tpis_gt2_records_birth_notifications <- executeQuery(ms_conn,
                                                       sql_query = paste("SELECT COUNT(*) FROM (",
                                                                         "SELECT COUNT(*) AS cnt",
                                                                         "FROM FILE0184887_birth_notifications",
                                                                         "GROUP BY token_person_id",
                                                                         ") AS sq WHERE cnt > 1;"))
  stopifnot(tpis_gt2_records_birth_notifications == 0)

  sql_birth_notifications <- paste("SELECT [TOKEN_PERSON_ID],",
                                   "CAST(CONCAT(SUBSTRING([BABY_BIRTH_DATE], 3, 4),",
                                   "SUBSTRING([BABY_BIRTH_DATE], 1, 2), '01') AS DATE) AS notification_dob,",
                                   "[BABY_ETHNICITY] AS notification_ethnicity,",
                                   "[BABY_SEX] AS notification_sex,",
                                   "[LIVE_STILL] AS notification_stillbirth,",
                                   "[NUM_BIRTHS] AS notification_num_births",
                                   "FROM [FILE0184887_birth_notifications];")


  birth_notifications <- executeQuery(ms_conn, sql_birth_notifications)

  birth_notifications_filepath <- writeParquetFile(birth_notifications,
                                   dir_path = paste0(base_directory_path,
                                                     "birth_notifications"),
                                   filename = "birth_notifications")

  rm(birth_notifications)
  gc()

  sql_infant_summary_registrations_notifications <- paste("CREATE TABLE birth_cohort AS (",
                                                          "SELECT ir.*,",
                                                          "notif.notification_dob,",
                                                          "notif.notification_ethnicity,",
                                                          "notif.notification_sex,",
                                                          "notif.notification_stillbirth,",
                                                          "notif.notification_num_births,",
                                                          "FROM",
                                                          "infant_records_summary_with_registrations AS ir",
                                                          "LEFT JOIN (",
                                                          "SELECT * FROM",
                                                          paste0("read_parquet('",
                                                                 birth_notifications_filepath,
                                                                 "')) AS notif"),
                                                          "ON (ir.token_person_id = notif.token_person_id));",
                                                          "DROP TABLE IF EXISTS infant_records_summary_with_registrations;")

  res <- executeQuery(ddb_conn,
                      sql_query = sql_infant_summary_registrations_notifications,
                      query_type = "SEND")
  gc()


  # DuckDB "COPY TO" is very slow, this is faster (though perhaps less stable at very large scale)
  birth_cohort <- executeQuery(ddb_conn,
                               sql_query = paste("SELECT bc.*,",
                                                 "id.dfe_id,",
                                                 "id.dfe_id_problematic",
                                                 "FROM birth_cohort AS bc",
                                                 "LEFT JOIN",
                                                 paste0("read_parquet('",
                                                        nhs_dfe_id_lookup_path,
                                                        "') AS id"),
                                                 "ON bc.token_person_id = id.nhs_id;"))

  write_result <- writeParquetFile(birth_cohort,
                                   dir_path = paste0(base_directory_path,
                                                     birth_cohort_name),
                                   filename = birth_cohort_name)
  rm(birth_cohort)
  gc()

  res <- executeQuery(ddb_conn,
                      sql_query = "DROP TABLE IF EXISTS birth_cohort;",
                      query_type = "SEND")
  gc()

  deleteFolderOfFile(paste0(base_directory_path,
                            "birth_notifications/birth_notifications.parquet"))
  deleteFolderOfFile(births_deaths_path)

  return(write_result)
}


