saveEthnicityGeoInfo <- function(ddb_conn,
                                  echoccs_data_directory_path,
                                  infants_records_name,
                                  ethnicity_geo_name) {

  # ddb_conn <- duckdb_conn

  # Infant records

  ir_filepath <- paste0(echoccs_data_directory_path,
                        infants_records_name,
                        "/",
                        infants_records_name,
                        ".parquet")

  date_fields <- c("admidate",
                   "disdate",
                   "epiend",
                   "epistart")

  res <- executeQuery(ddb_conn,
                      sql_query = paste("DROP TABLE IF EXISTS ethnos_msoa_raw;",
                                        "CREATE TABLE ethnos_msoa_raw AS (",
                                        "SELECT token_person_id,",
                                        paste0("TRY_CAST(CASE WHEN ",
                                               date_fields,
                                               " IN ('1800-01-01', '1801-01-01') ",
                                               "THEN NULL ELSE ",
                                               date_fields,
                                               " END AS DATE) AS ",
                                               date_fields,
                                               collapse = ", "),
                                        ", ",
                                        paste0("TRY_CAST(CASE WHEN mydob IN ",
                                               "('011800', '011801') THEN NULL ",
                                               "ELSE CONCAT(",
                                               "SUBSTRING(mydob, 3, 4), '-', ",
                                               "SUBSTRING(mydob, 1, 2), '-01') END AS DATE) ",
                                               "AS mydob,"),
                                        "CASE WHEN ethnos IN (",
                                        paste0("'",
                                               0:9,
                                               "'",
                                               collapse = ", "),
                                        ") THEN 1995",
                                        "WHEN ethnos IN (",
                                        paste0("'",
                                               LETTERS[c(1:8, 10:14, 16, 18:19, 24, 26)],
                                               "'",
                                               collapse = ", "),
                                        ") THEN 2001",
                                        "WHEN ethnos = '99' AND reporting_year_start < 2013 THEN 1995",
                                        "WHEN ethnos = '99' AND reporting_year_start >= 2013 THEN 2001",
                                        "ELSE NULL END AS ethnicity_coding_system,",
                                        "CASE WHEN ethnos = '0' THEN 'A'",
                                        "WHEN ethnos = '1' THEN 'M'",
                                        "WHEN ethnos = '2' THEN 'N'",
                                        "WHEN ethnos = '3' THEN 'P'",
                                        "WHEN ethnos = '4' THEN 'H'",
                                        "WHEN ethnos = '5' THEN 'J'",
                                        "WHEN ethnos = '6' THEN 'K'",
                                        "WHEN ethnos = '7' THEN 'R'",
                                        "WHEN ethnos = '8' THEN '8'",
                                        "WHEN ethnos IN (",
                                        paste0("'",
                                               LETTERS[c(1:8, 10:14, 16, 18:19)],
                                               "'",
                                               collapse = ", "),
                                        ") THEN ethnos",
                                        "ELSE NULL END AS ethnicity,",
                                        "CASE WHEN oacode6 = '' THEN NULL ELSE oacode6 END AS oacode6,",
                                        "CASE WHEN msoa01 = '' THEN NULL ELSE msoa01 END AS msoa01,",
                                        "CASE WHEN msoa11 = '' THEN NULL ELSE msoa11 END AS msoa11",
                                        "FROM",
                                        paste0("read_parquet('",
                                               ir_filepath,
                                               "')"),
                                        ");"),
                      query_type = "SEND")

  res <- executeQuery(ddb_conn,
                      sql_query = paste("DROP TABLE IF EXISTS ethnos_msoa;",
                                        "CREATE TABLE ethnos_msoa AS (",
                                        "SELECT *,",
                                        "CASE WHEN ethnicity IN ('A', 'B', 'C') THEN 'White'",
                                        "WHEN ethnicity IN ('D', 'E', 'F', 'G') THEN 'Mixed or multiple ethnic groups'",
                                        "WHEN ethnicity IN ('H', 'J', 'K', 'L', 'R') THEN 'Asian or Asian British'",
                                        "WHEN ethnicity IN ('M', 'N', 'P') THEN 'Black, Black British, Caribbean or African'",
                                        "WHEN ethnicity  = 'S' THEN 'Other ethnic group'",
                                        "WHEN ethnicity  = '8' THEN 'Mixed or multiple ethnic groups or Other ethnic group'",
                                        "ELSE NULL END AS ethnicity_broad,",
                                        "LEAST(",
                                        paste0(date_fields,
                                               collapse = ", "),
                                        ") AS episode_min_date",
                                        "FROM ethnos_msoa_raw);",
                                        "DROP TABLE IF EXISTS ethnos_msoa_raw;"),
                      query_type = "SEND")

  ethnicity_data <- executeQuery(ddb_conn,
                                 sql_query = paste("SELECT",
                                                   "token_person_id,",
                                                   "ethnicity_broad AS eth_ethnicity_broad,",
                                                   "ethnicity_coding_system AS eth_ethnicity_coding_system,",
                                                   "months_since_dob AS eth_months_since_dob,",
                                                   "ethnicity_broad_n AS eth_ethnicity_broad_n",
                                                   "FROM (",
                                                   "SELECT",
                                                   "dets.token_person_id,",
                                                   "dets.ethnicity_broad,",
                                                   "dets.ethnicity_coding_system,",
                                                   "dets.months_since_dob,",
                                                   "ROW_NUMBER() OVER (PARTITION BY dets.token_person_id ORDER BY ABS(dets.months_since_dob), dets.tpi_order) AS eth_order,",
                                                   "agg.ethnicity_broad_n",
                                                   "FROM (",
                                                   "SELECT",
                                                   "token_person_id,",
                                                   "ethnicity_broad,",
                                                   "ethnicity_coding_system,",
                                                   "ROW_NUMBER() OVER (PARTITION BY token_person_id ORDER BY episode_min_date, admidate, epistart, epiend) AS tpi_order,",
                                                   "DATE_DIFF('MONTH', mydob, episode_min_date) AS months_since_dob",
                                                   "FROM ethnos_msoa",
                                                   "WHERE ethnicity IS NOT NULL) AS dets",
                                                   "INNER JOIN (",
                                                   "SELECT token_person_id,",
                                                   "COUNT(DISTINCT ethnicity_broad) AS ethnicity_broad_n",
                                                   "FROM ethnos_msoa",
                                                   "WHERE ethnicity IS NOT NULL",
                                                   "GROUP BY token_person_id) AS agg",
                                                   "ON dets.token_person_id = agg.token_person_id) AS q1",
                                                   "WHERE eth_order = 1;"))

  setDT(ethnicity_data)

  geo_data <- executeQuery(ddb_conn,
                                 sql_query = paste("SELECT",
                                                   "token_person_id,",
                                                   "oacode6 AS geo_oacode6,",
                                                   "msoa01 AS geo_msoa01,",
                                                   "msoa11 AS geo_msoa11,",
                                                   "months_since_dob AS geo_months_since_dob",
                                                   "FROM (",
                                                   "SELECT",
                                                   "token_person_id,",
                                                   "oacode6,",
                                                   "msoa01,",
                                                   "msoa11,",
                                                   "months_since_dob,",
                                                   "ROW_NUMBER() OVER (PARTITION BY token_person_id ORDER BY ABS(months_since_dob), tpi_order) AS geo_order",
                                                   "FROM (",
                                                   "SELECT",
                                                   "token_person_id,",
                                                   "oacode6,",
                                                   "msoa01,",
                                                   "msoa11,",
                                                   "ROW_NUMBER() OVER (PARTITION BY token_person_id ORDER BY episode_min_date, admidate, epistart, epiend) AS tpi_order,",
                                                   "DATE_DIFF('MONTH', mydob, episode_min_date) AS months_since_dob",
                                                   "FROM ethnos_msoa",
                                                   "WHERE msoa01 IS NOT NULL) AS q1) AS q2 WHERE geo_order = 1;"))

  setDT(geo_data)

  res <- executeQuery(ddb_conn,
                      sql_query = "DROP TABLE IF EXISTS ethnos_msoa;",
                      query_type = "SEND")

  ethnicity_data <- merge(ethnicity_data,
                          geo_data,
                          by = "token_person_id",
                          all = TRUE)

  ethnicity_geo_data_filepath <- writeParquetFile(ethnicity_data,
                                                 dir_path = paste0(echoccs_data_directory_path,
                                                                   ethnicity_geo_name),
                                                 filename = ethnicity_geo_name)

  return(ethnicity_geo_data_filepath)
}
